#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- nginx "$@"
else

	echo "Set custom nginx configurations"
	envsubst < /docker/configurations/nginx/conf.d/default.conf > /etc/nginx/conf.d/default.conf

	exec "$@"

fi
