#!/bin/sh
set -e

# first arg is `-f` or `--some-option`
if [ "${1#-}" != "$1" ]; then
	set -- nginx "$@"
else

	envsubst '${VHOST_ROOT},${VHOST_INDEX},${NGINX_CLIENTMAXBODYSIZE},${FPM_LISTEN_ADDRESS}' < /docker/config/conf.d/default.conf > /etc/nginx/conf.d/default.conf

fi

exec "$@"